ALTER TABLE section_settings
ADD COLUMN IF NOT EXISTS pdf_sub_kegiatan TEXT DEFAULT 'NORMALISASI / RESTORASI SUNGAI',
ADD COLUMN IF NOT EXISTS pdf_nama_staf TEXT DEFAULT 'PANGESTU EKA DEWANTO W, A.Md.T',
ADD COLUMN IF NOT EXISTS pdf_nip_staf TEXT DEFAULT '19980711 202204 1 001';
