-- Migration 6: Tambah kolom pdf_kegiatan dan pdf_program ke section_settings
ALTER TABLE section_settings
ADD COLUMN IF NOT EXISTS pdf_program TEXT DEFAULT 'PENGELOLAAN SUMBER DAYA AIR',
ADD COLUMN IF NOT EXISTS pdf_kegiatan TEXT DEFAULT 'PENGELOLAAN SDA DAN BANGUNAN PENGAMAN PANTAI PADA WILAYAH SUNGAI (WS) DALAM 1 (SATU) DAERAH KABUPATEN/KOTA';
